name: Run Selenium Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,6,12,18 * * *'  # co 6 godzin (UTC)

permissions:
  contents: read

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas geopy openpyxl beautifulsoup4 requests webdriver-manager python-dotenv

      - name: Run scraper
        env:
            ONEDRIVE_CLIENT_ID: ${{ secrets.ONEDRIVE_CLIENT_ID }}
            ONEDRIVE_TENANT_ID: ${{ secrets.ONEDRIVE_TENANT_ID }}
            ONEDRIVE_CLIENT_SECRET: ${{ secrets.ONEDRIVE_CLIENT_SECRET }}
            ONEDRIVE_USER_ID: ${{ secrets.ONEDRIVE_USER_ID }}
        run: python script.py