name: Run Selenium Scraper

on:
  workflow_dispatch:        # Ręczne uruchomienie
  schedule:
    - cron: '0 7 * * *'     # Codziennie o 07:00 UTC (09:00 w Polsce)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas geopy openpyxl webdriver-manager

      - name: Run Selenium scraper
        run: python script.py  # <-- nazwa pliku

      - name: Commit and push Excel file
        run: |
          git add wyniki_ofert_z_filtra.xlsx || true
          git commit -m "Automatyczna aktualizacja Excela [$(date '+%Y-%m-%d %H:%M:%S')]" || echo "Brak zmian do commitowania"
          git pull --rebase origin main
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main