name: Run Scraper

on:
  workflow_dispatch:    # Manual trigger
  schedule:
    - cron: "0 6 * * *" # Runs every day at 6:00 UTC (adjust if needed)

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Install system dependencies (Firefox and Geckodriver)
      - name: Install Firefox and Geckodriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox-esr
          # Install Geckodriver (if not already present)
          GECKO_VER=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep tag_name | cut -d '"' -f4)
          wget -q https://github.com/mozilla/geckodriver/releases/download/$GECKO_VER/geckodriver-$GECKO_VER-linux64.tar.gz
          tar -xzf geckodriver-*-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version
          firefox --version

      # 4. Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas geopy openpyxl webdriver-manager

      # 5. Run the scraper script
      - name: Run scraper
        run: |
          python script.py

      # 6. Commit and push Excel results back to the repository
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add wyniki_ofert_z_filtra.xlsx
          git commit -m "Update Excel data [CI skip]" || echo "No changes to commit"
          git push